services:
  freakfightsfan.api:
    image: ${DOCKER_REGISTRY-}freakfightsfanapi
    container_name: freakfightsfan.api
    build:
      context: .
      dockerfile: FreakFightsFan.Api/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./FreakFightsFan.Api/Logging/Logs:/app/Logging/Logs
      - ./FreakFightsFan.Api/wwwroot/images:/app/wwwroot/images
      - ./FreakFightsFan.Api/wwwroot/images_federations:/app/wwwroot/images_federations
  
  freakfightsfan.blazor:
    image: ${DOCKER_REGISTRY-}freakfightsfanblazor
    container_name: freakfightsfan.blazor
    build:
      context: .
      dockerfile: FreakFightsFan.Blazor/Dockerfile
    ports:
      - 7000:80
    environment:
      - ASPNETCORE_URLS=http://+:7000
      - ASPNETCORE_HTTP_PORTS=7000
      - ASPNETCORE_ENVIRONMENT=Development

  freakfightsfan.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: freakfightsfan.database
    shm_size: 4gb
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: 'Password1!'
      ACCEPT_EULA: 'Y'
    volumes:
      - mssql_volume:/var/opt/mssql

  freakfightsfan.seq:
    image: datalust/seq:latest
    container_name: freakfightsfan.seq
    ports:
      - 5341:5341
      - 8081:80
    environment:
      ACCEPT_EULA: 'Y'

volumes:
  mssql_volume:
    driver: local
