version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: fff-mssql
    shm_size: 4gb
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: 'Password1!'
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_volume:/var/opt/mssql
  seq:
    image: datalust/seq:latest
    container_name: fff-seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 5341:5341
      - 8081:80

volumes:
  mssql_volume:
    driver: local
